### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by SergeyMC9730** [Sparker-99/string-progressbar#6]
I got this error: `(node:154847) UnhandledPromiseRejectionWarning: Error: Size is not an integer`
... using these splitBar's arguments:
 
- **Total**: 1530
- **Current**: 0
- **_Options_**: 
   - **Size**: 10
   
**Full error**:
```
(node:154847) UnhandledPromiseRejectionWarning: Error: Size is not an integer
    at Object.splitBar (/home/dog/bomedev/node_modules/string-progressbar/index.js:6:25)
    at Client.<anonymous> (/home/dog/bomedev/main.js:95:148)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:154847) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:154847) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Sparker-99** [comment]
```
let { splitBar } = require("string-progressbar");

splitBar(1530, 0, 10)[0];
```

Also from next time kindly use discord linked in readme for support.

**Comment by SergeyMC9730** [comment]
thanks!
